### ISSUE TITLE
[Global] Fix background image

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#1]
Background image used is incorrect. It must be repeating pattern, which can be taken from [here](https://projects.invisionapp.com/d/main#/projects/prototypes/11780436/assets/68568664).

![1](https://user-images.githubusercontent.com/9034705/33020799-9946afc6-ce10-11e7-8bc1-3de3e8a067bf.jpg)

**Comment by gd-ademus** [comment]
https://github.com/gd-ademus/gridu-css/blob/master/components/images/sale.jpg

**Comment by snovikov-gd** [comment]
Confirmed
