### ISSUE TITLE
Add background to product page

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#10]
Add missing background to the product pages:

![12](https://user-images.githubusercontent.com/9034705/33023241-8c1e9eaa-ce18-11e7-82ce-0a6af2eba325.jpg)

**Comment by gd-ademus** [comment]
https://github.com/gd-ademus/gridu-css/commit/c7035af7b7a11e96c0af942aa952f4ccd4578b50

**Comment by snovikov-gd** [comment]
Confirmed
