### ISSUE TITLE
[Global] Add default font family

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#11]
https://github.com/gd-ademus/gridu-css/blob/33dadc28649da415ccea00025d97ac20a378ef9b/components/css/base.css#L5

Add [default font family](https://www.w3schools.com/cssref/pr_font_font-family.asp) everywhere when defining font to provide fallback if "PT Sans" is not available. It is `sans-serif` in your case.

**Comment by gd-ademus** [comment]
7ce52898141aaecf85d5d3fe0de7cedd21a1eeb3
