### ISSUE TITLE
[Global] Reorganize styles and forder structure

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#12]
Current project structure is not quite clear to me. I see `/components` folder at the top level with all the CSS and assets inside:

![components2](https://user-images.githubusercontent.com/9034705/34208985-7098b846-e5a1-11e7-81c8-dc8ae173c482.png)

At the same time I do not see _components_ files here except `modal.css`. I would suggest to reorganize folder structure to get something like this:
```
/css
    /components
        button.css
        select.css
        radio.css
        checkbox.css
        ...
    /pages
        login.css
        main.css
        product.css
        ...
    style.css (contains all nested styles)
/images
index.html
...
```

**Comment by gd-ademus** [comment]
9050fd51bd1103d44fb39c63c3a84a4d731f7916
