### ISSUE TITLE
[Global] Add `for` attribute for labels

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#13]
When you do not wrap input by label tag, you must use id for this input and for attribute for this label.

Wrong:
```
<label class="login-label">Your Login:</label>
<input class="login-input" type="text" pattern="[A-Za-z0-9]{0,10}"/>
```

Correct:
```
<label for="yourLogin" class="login-label">Your Login:</label>
<input id="yourLogin" class="login-input" type="text" pattern="[A-Za-z0-9]{0,10}"/>
```

Otherwise, clicking on label will not trigger click event on corresponding select.

**Comment by gd-ademus** [comment]
8cc5444ff0f022221a2855eb2d51c08d92773bae
