### ISSUE TITLE
[Global] Do not rely on spaces/line breaks in markup

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#16]
Get rid of such lind of markup:
![l4](https://user-images.githubusercontent.com/9034705/34212105-5428b822-e5ac-11e7-88aa-b2a51669db7c.png)

I guess you've done it to avoid unexpected spaces between stars. It's better and more readable to set `font-size: 0` for `.star-box`.

**Comment by gd-ademus** [comment]
efabb5710270529edf37ed177c79d042da015dbb
