### ISSUE TITLE
[Global] Get rid of anonymous wrappers

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#17]
Do not wrap content by `div` or `span` without class or id, do not use cascade styling since you're not using any CSS scoping features(js framework CSS scoping polyfills, native web components, etc).

![l5](https://user-images.githubusercontent.com/9034705/34212569-be17af4e-e5ad-11e7-9ad7-9d562b874340.png)

The best way is to use any popular naming convention, like [BEM](https://ru.bem.info/methodology/quick-start/) or your own, that prevents using cascade.

In your case, to save time, you can just add meaningful class names to divs and stylize them by these class names.

**Comment by gd-ademus** [comment]
362a169031a38ece51e70cd453bc5cd83b5473a9
