### ISSUE TITLE
[Global] Fix header and footer

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#2]
Make header and footer styles to have 100% width.

![2](https://user-images.githubusercontent.com/9034705/33021058-98368592-ce11-11e7-99b7-a748c017298c.jpg)

**Comment by gd-ademus** [comment]
https://github.com/gd-ademus/gridu-css/commit/913feccfd801db0c544b34493ae6a365e3bb3177

**Comment by snovikov-gd** [comment]
Confirmed
