### ISSUE TITLE
[Global] Fix modal styles

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#3]
1. Fix modal background image to [the correct one](https://projects.invisionapp.com/d/main#/projects/prototypes/11780436/assets/69951730).

2. Make background overlay to be darken(not lighten as it's now).
![4](https://user-images.githubusercontent.com/9034705/33021645-ac674072-ce13-11e7-83d7-b816064aaacb.jpg)

3. Fix incorrect font family for the 'Success Modal Body' and all similar modals:
![5](https://user-images.githubusercontent.com/9034705/33021809-2f24a7b6-ce14-11e7-89f8-f3fc077cecb8.jpg)

**Comment by gd-ademus** [comment]
https://github.com/gd-ademus/gridu-css/commit/451c58879a95b006922e5a2f0808e3e0b91da2b4

**Comment by snovikov-gd** [comment]
Confirmed
