### ISSUE TITLE
Fix space between stars

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#4]
Fix space between stars according to design specs

![6](https://user-images.githubusercontent.com/9034705/33022330-e5524420-ce15-11e7-8199-19dd6d0d29f1.jpg)

**Comment by gd-ademus** [comment]
https://github.com/gd-ademus/gridu-css/commit/b8b327651fe95422d20859a987281cc0fd0958ba

**Comment by snovikov-gd** [comment]
Confirmed
