### ISSUE TITLE
Add background to product card

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#5]
Add missing background to product card:

![7](https://user-images.githubusercontent.com/9034705/33022449-4ef41688-ce16-11e7-943e-6af8369f6da4.jpg)

**Comment by gd-ademus** [comment]
https://github.com/gd-ademus/gridu-css/commit/913feccfd801db0c544b34493ae6a365e3bb3177

**Comment by snovikov-gd** [comment]
Confirmed
