### ISSUE TITLE
Make filters button pressed when opened

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#6]
Make filters button pressed when opened(according to design specs):

![8](https://user-images.githubusercontent.com/9034705/33022556-a4f621fc-ce16-11e7-8908-ea92b5839b3d.jpg)

**Comment by gd-ademus** [comment]
https://github.com/gd-ademus/gridu-css/commit/43bc066e5be525846965900bc8207a9281f9e9ac

**Comment by snovikov-gd** [comment]
Confirmed
