### ISSUE TITLE
[Global] Label all radio/checkboxes

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#7]
Due to accessibility reasons, make labels for radio buttons and checkboxes clickable:

![9](https://user-images.githubusercontent.com/9034705/33022766-4cad55f0-ce17-11e7-98e0-fb016569de7c.jpg)

**Comment by gd-ademus** [comment]
https://github.com/gd-ademus/gridu-css/commit/33dadc28649da415ccea00025d97ac20a378ef9b

**Comment by snovikov-gd** [comment]
Confirmed
