### ISSUE TITLE
Eliminate login window's input icons shift

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#8]
Eliminate login window's input icons shift when focus/blur:

![10](https://user-images.githubusercontent.com/9034705/33022927-b6c24afe-ce17-11e7-9e78-bb58e07845c7.jpg)

**Comment by gd-ademus** [comment]
https://github.com/gd-ademus/gridu-css/commit/d95df053b29dca51f59d75344f50e610d93fd5c5

**Comment by snovikov-gd** [comment]
Confirmed
