### ISSUE TITLE
Fix 'Buy' button styles

### ISSUE THREAD

**Issue by snovikov-gd** [gd-ademus/gridu-css#9]
Fix 'Buy' button styles everywhere:

![11](https://user-images.githubusercontent.com/9034705/33023153-50669b74-ce18-11e7-896d-22996635cd18.jpg)

**Comment by gd-ademus** [comment]
https://github.com/gd-ademus/gridu-css/commit/c7035af7b7a11e96c0af942aa952f4ccd4578b50

**Comment by snovikov-gd** [comment]
Confirmed
